"""add hashed password to users

Revision ID: 07bd4765ea99
Revises: 078f9c2baa3b
Create Date: 2026-09-16 15:02:05.127395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bd4765ea99'
down_revision: Union[str, Sequence[str], None] = '078f9c2baa3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'hashed_password',
        sa.String(length=255),
        nullable=True,
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
