"""ajouter le type d'article et rendre le mot de passe obligatoire

Revision ID: 1504eee98b4c
Revises: 5010d59ca0bb
Create Date: 2026-09-28 13:47:13.049477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1504eee98b4c'
down_revision: Union[str, Sequence[str], None] = '5010d59ca0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('item_type', sa.String(length=20), server_default='product', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'item_type')
    # ### end Alembic commands ###
